# -*- coding: utf-8 -*-
"""Latihan fuzzy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAuVfFwaRZnKbjOsklA7nkxWGLQ0XfVg
"""

import numpy as np
import matplotlib.pyplot as plt

def triangular(x, a, b, c):
    if x <= a or x >= c:
        return 0
    elif a < x <= b:
        return (x-a)/(b-a)
    elif b < x < c:
        return (c-x)/(c-b)

def trapezoid(x, a, b, c, d):
    if x <= a or x >= d:
        return 0
    elif a < x <= b:
        return (x-a)/(b-a)
    elif b < x <= c:
        return 1
    elif c < x < d:
        return (d-x)/(d-c)

    """
    Calculates the membership value for a triangular fuzzy function using if/elif/else.

    Parameters:
    x (float or np.array): The input value(s).
    a (float): The left-most X point, paired with y value d.
    b (float): The middle X point, paired with Y value of 1.
    c (float): The right-most X point, paired with Y value e.
    d (float): The y-value at point a.

    Returns:
    float or np.array: The membership value(s).
    """
print("Tugas-Kecerdasan-Buatan-2")
print("Nama: Irwansyah Indra Prayoga")
print("NRP: 6022251086")
print("-")
print("Temperature Input = 32.5")
print("-")
Temperature_Ruang = 32.5

dingin = trapezoid(Temperature_Ruang,0,0,15,25)
sedang = triangular(Temperature_Ruang,15,25,35)
panas = trapezoid(Temperature_Ruang,25,35,50,50)

print("Dingin : 0%", dingin)
print("Sedang :25%", sedang)
print("Panas :75%", panas)

x = np.linspace(0,50,200)

cold = [trapezoid(i,0,0,15,25) for i in x]
medium = [triangular(i,15,25,35) for i in x]
hot = [trapezoid(i,25,35,50,50) for i in x]

plt.figure(figsize=(8,5))
plt.plot(x, cold, color='red', label="Dingin")
plt.axvline(32.5,color='orange',linestyle="--")
plt.legend()
plt.xlabel("Temperature t")
plt.ylabel("μ_D(t)")
plt.show()

plt.figure(figsize=(8,5))
plt.plot(x, medium, color='green', label="Sedang")
plt.axvline(32.5,color='orange',linestyle="--")
plt.legend()
plt.xlabel("Temperature t")
plt.ylabel("μ_D(t)")
plt.show()

plt.figure(figsize=(8,5))
plt.plot(x, hot, color='royalblue', label="Panas")
plt.axvline(32.5,color='orange',linestyle="--")
plt.legend()
plt.xlabel("Temperature t")
plt.ylabel("μ_D(t)")
plt.show()